apiVersion: v1
kind: Service
metadata:
  name: kyt-api
  namespace: kyt-engine
  labels:
    app.kubernetes.io/name: kyt-engine
    app.kubernetes.io/component: api
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: kyt-engine
    app.kubernetes.io/component: api
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
      nodePort: 30080
